### ISSUE TITLE
The guide is not so simple... what should I do to run it? can you please add more info on how to do it?

### ISSUE THREAD

**Issue by search620** [Fictiverse/StableDiffusion-Windows-GUI#6]

**Comment by Fictiverse** [comment]
Hi, i added a small guide for the prompt tab

**Comment by search620** [comment]
Hey, thank you for your effort but I mean a guide on how to install the program? I did try and end up with a popup window that requested to open a file but this window doesn't have a browse option. please check it.

**Comment by Fictiverse** [comment]
Try to setup your env path manualy on the **Settings.ini** file

like...
```
[Settings]
EnvPath=S:\Python\anaconda3\envs\ldm
```

**Comment by bbecausereasonss** [comment]
I'm still lost as to how to launch the GUI.

**Comment by CmdrMichael** [comment]
I can not get it to work:
I installed stable-diffusion according to the original documentation.  It is working from the prompt.

My anaconda path:
C:\Users\username\.conda\envs\ldm
When I set this path and try to generate a picture, the following error message is displayed:
C:\Users\username\.conda\envs\ldm\scripts\txt2img.py not found.
The text2img.py was never in that directory but in the stable diffusion directory which is F:\stable-diffusion\stable-diffusion-main\scripts in my case.

**Comment by altmank** [comment]
I still can't figure out how to get it to open either, it wants some location but I've tried many paths and none seem to work. Just keeps prompting me for "Stable Diffusion location" I've given it several locations, including an 'ldm' location.

**Comment by jlitz** [comment]
Yea Im  confused too on opening the program.. 

 I already had previously installed the CMDR2 GUI in the C:\Stable Diffusion directory which works off a cmd file.

**Comment by Tom1827** [comment]
> I can not get it to work: I installed stable-diffusion according to the original documentation. It is working from the prompt.
> 
> My anaconda path: C:\Users\username\.conda\envs\ldm When I set this path and try to generate a picture, the following error message is displayed: C:\Users\username\.conda\envs\ldm\scripts\txt2img.py not found. The text2img.py was never in that directory but in the stable diffusion directory which is F:\stable-diffusion\stable-diffusion-main\scripts in my case.

Similar experience here.  I have a miniconda installation at C:\ProgramData\Miniconda3\envs\ldo and a working webUI (from a early build of https://github.com/sd-webui/stable-diffusion-webui) with scripts (including text2img.py) at another lcoation (currently C:\Users\<user>\Downloads\stable-diffusion-main).

**Comment by jlitz** [comment]
i am using  cmdr2 from github works fine   takes a while to install

**Comment by argamate** [comment]
> > I can not get it to work: I installed stable-diffusion according to the original documentation. It is working from the prompt.
> > My anaconda path: C:\Users\username.conda\envs\ldm When I set this path and try to generate a picture, the following error message is displayed: C:\Users\username.conda\envs\ldm\scripts\txt2img.py not found. The text2img.py was never in that directory but in the stable diffusion directory which is F:\stable-diffusion\stable-diffusion-main\scripts in my case.
> 
> Similar experience here. I have a miniconda installation at C:\ProgramData\Miniconda3\envs\ldo and a working webUI (from a early build of https://github.com/sd-webui/stable-diffusion-webui) with scripts (including text2img.py) at another lcoation (currently C:\Users<user>\Downloads\stable-diffusion-main).

Happens on Anaconda 3 as well for me

**Comment by Fictiverse** [comment]
I will check how to solve your problems today.

**Comment by DarksealStudios** [comment]
so lost. I have gui 0.1 working just fine. I have no clue how to use this one to get it installed. Do i merge the folders? If only there was a friendly youtube video for someone not familiar with conda at all, to help people get this installed. Please help us obi wan kenobi, highly detailed, portrait, bokeh, i s o 1 0 0,.

**Comment by Fictiverse** [comment]
Your stable diffusion path should look like :

`[AnacondaInstallationPath]/envs/[StableDiffusionEnvName]` and your script folders should be in
 `[AnacondaInstallationPath]/envs/[StableDiffusionEnvName]/Scripts/img2img.py`

But no worry, i wil modify it to make it compatible with all conda installations

**Comment by argamate** [comment]
Can confirm that it now works in the latest 0.9 version.
Just one thing in the settings it says txt2txt instead of txt2img
Thanks!

**Comment by bucketcat** [comment]
I think I found the problem. He forgot to include the .EXE in the main repo haha.

Edit: can be found here https://github.com/Fictiverse/StableDiffusion-Windows-GUI/releases/tag/0.9
Might be the worst documented project I have ever seen. Please spend like 60-90 minutes documenting important stuff and maybe make a screenshot step-by-step guide of you going through set up through git by installing it on a VM or something. Can help you spot missing files if you have to go through the new user experience yourself ;).

Edit 2: I see img2morph path in the options of your GUI, I haven't seen anything relating to img2morph before. Is that for future compatibility or is that already an SD feature?

**Comment by Fictiverse** [comment]
I know, sorry about that but i do a lot of changes so i will make a complete doc when i release 1.0
